### PR TITLE
Launcher 8.0 path patch

### PR DESCRIPTION
**Pull request by ghost**
Launcher 8.0 path has changed.
This patch correct it.

### CODE REVIEW

**Comment by hagenest** [comment]
I'm not a reviewer or anything but I can confirm that this branch works for me on NixOS 23.05. Thank you :)

**Comment by fkollmann** [comment]
confirmed +1

**Comment by fkollmann** [comment]
friendly reminder :)

**Comment by th3r00t** [comment]
Any chance we can get this merged?

**Comment by tsandrini** [comment]
+1 from me as well ... maybe we should look for another maintainer or what's the concensus?

**Pull request merged**
